### ISSUE TITLE
Port of feature to Chrome plugin

### ISSUE THREAD

**Issue by OscarVanL** [ItsNickBarry/netflix-max-bitrate#3]
Hi,

I recently started using a Chrome plugin called [netflix-1080p](https://github.com/truedread/netflix-1080p) to unlock 1080p on Netflix in Chrome. 

I was having issues where Netflix would arbitrarily drop the bitrate through a stream, so despite having unlocked these nice high bitrates, it would become crappy quality after 15 minutes or so. I found your extension to solve this problem, and have [made a pull request on that project](https://github.com/truedread/netflix-1080p/pull/71) to merge your javascript functionality into that project.

I've linked to your project in the pull request, but if there's anything else you'd like me to do please let me know.

Oscar

**Comment by ItsNickBarry** [comment]
@OscarVanL I'm aware of that project, but I think this feature might be considered to fall outside of its scope.  If your pull request is accepted, I'll add a link to the readme.  Thanks.

**Comment by OscarVanL** [comment]
Perhaps. I added it as an optional feature in the settings next to the option to set 5.1 surround. We'll see.

I think it does fit into the theme of the plugin. It unlocks 1080p (improved visuals), it has an option to use unlock 5.1 surround (improved audio), so an extra option to set the best bitrate (improved visuals) just makes sense as an addition to me.

**Comment by ItsNickBarry** [comment]
Looks like it's been merged.  I've updated the readme to reflect this.  Thanks.

**Comment by OscarVanL** [comment]
Thanks :)
